{% set name = "Thresher" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: '{{ version }}'

build:
  number: 0
  noarch: generic
  run_exports:
    - {{ pin_subpackage("thresher", max_pin="x") }}
  entry_points:
    - thresher=cli:main

requirements:
  run:
    - python >=3.11,<=3.13
    - pandas =2.2.3
    - snakemake =8.26.0

test:
  imports:
    - snakemake
    - pandas