rule study_snp_matrix_new_full:
    conda:
        os.path.join(BASE_PATH,"envs/R_env.yaml")
    input:
        study_concatenated_reports = expand(os.path.join(config["output"], "mummer4_study", "{genome_name}_concatenated.report"),genome_name=new_genome_path_dict.keys())
    output:
        # In order to make the new_full output compatible with other run of new_full
        # I keep the same output file name as the snp matrix generated by full-pipeline
        study_snp_matrix_new = os.path.join(config["output"],"mummer4_study","study_snp_matrix.RDS")
    params:
        original_metadata = config["original_metadata"],
        new_metadata = config["new_metadata"],
        report_dir = os.path.join(config["output"],"mummer4_study"),
        snp_coverage_threshold = config["snp_coverage_threshold"],
        original_snp_matrix = os.path.join(config["thresher_output"], "mummer4_study", "study_snp_matrix.RDS")
    threads:
        config["threads"]
    script:
        # Suffix is new but not new_full because both new_snps and new_full use the same script here
        os.path.join(BASE_PATH,"scripts","study_snp_matrix_new.R")

rule global_snp_matrix_new_full:
    conda:
        os.path.join(BASE_PATH,"envs/R_env.yaml")
    input:
        actual_download_topgenomes = os.path.join(config["output"],"datasets_topgenomes","actual_download_topgenomes.txt"),
        global_concatenated_reports = expand(os.path.join(config["output"], "mummer4_global", "{genome_name}_concatenated.report"),genome_name=new_genome_path_dict.keys())
    output:
        # In order to make the new_full output compatible with other run of new_full
        # I keep the same output file name as the snp matrix generated by full-pipeline
        global_snp_matrix_new = os.path.join(config["output"], "mummer4_global", "global_snp_matrix.RDS")
    params:
        original_metadata = config["original_metadata"],
        new_metadata = config["new_metadata"],
        report_dir = os.path.join(config["output"],"mummer4_global"),
        original_snp_matrix = os.path.join(config["thresher_output"], "mummer4_global", "global_snp_matrix.RDS"),
        snp_coverage_threshold = config["snp_coverage_threshold"],
        whatsgnu_dir = os.path.join(config["output"],"whatsgnu")
    threads:
        config["threads"]
    script:
        os.path.join(BASE_PATH,"scripts","global_snp_matrix_new_full.R")